### ISSUE TITLE
Not Start

### ISSUE THREAD

**Issue by LUCASS7001** [stable-aman/discord-bot-template#1]
hey when i run `node .` or ` node index.js` not work

![image](https://github.com/ok-bro-calma/discord-bot-template/assets/132421057/7fa44d0f-3ef7-4576-b0d6-96081e47f34c)

**Comment by stable-aman** [comment]
Been inactive for too long
Apologies for the inconvenience, the issue has been resolved
Just update the following in your existing fork, I forgot to  update it after testing
![Screenshot_20230701_092349](https://github.com/stable-aman/discord-bot-template/assets/132000890/03f2b7b1-4640-45f9-9909-e0802a1ec7e1)
